/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABox: typeof import('./../components/a-box/a-box.vue')['default']
    ANavbar: typeof import('./../components/a-navbar/a-navbar.vue')['default']
    APage: typeof import('./../components/a-page/a-page.vue')['default']
    ATabbar: typeof import('./../components/a-tabbar/a-tabbar.vue')['default']
    ATest: typeof import('./../components/a-test/index.vue')['default']
    Navbar: typeof import('./../components/a-page/components/navbar.vue')['default']
    Tabbar: typeof import('./../components/a-page/components/tabbar.vue')['default']
  }
}
