/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BeeButton: typeof import('@/packages/components/bee-button/bee-button.vue')['default']
    BeeCell: typeof import('@/packages/components/bee-cell/bee-cell.vue')['default']
    BeeDocDemoBlock: typeof import('./../../components/bee-doc-demo-block/bee-doc-demo-block.vue')['default']
    BeeDocDemoSection: typeof import('./../../components/bee-doc-demo-section/bee-doc-demo-section.vue')['default']
    BeeIcon: typeof import('@/packages/components/bee-icon/bee-icon.vue')['default']
    BeeInput: typeof import('@/packages/components/bee-input/bee-input.vue')['default']
    BeeLoading: typeof import('@/packages/components/bee-loading/bee-loading.vue')['default']
  }
}
